### ISSUE TITLE
Praise the website

### ISSUE THREAD

**Issue by OmerZachar** [AdamLiberman/python_course_assignments#2]
Hi Adam!
Very cool design of the website! I really liked that you shared you're hobbies.
An idea for improvement is maybe to share which lab are you currently in and what is the research on.
Good luck:)
@szabgab

**Comment by AdamLiberman** [comment]
Thank you for your feedback! Since I am on the soldier's track I didn't start my rotations yet. Once I will, I will defenitely update the website.
